Protractor spike 2016 09 19
sturmf/regatta-angular2 pull request #1
Opened 2016-09-19 19:10 UTC by gesellc

This is just a initial test. Could you verify if the install description is complete?

_"It works on my machine..."_ :-)

2016-09-19 20:22 UTC, sturmf requested changes
Can you hook this tests up to the travis.ci?

2016-09-23 23:52 UTC, gesellc commented
Pew... so this is green now. But the travis configuration exploded. We should talk about refactoring this. 

@sturmf Added you as contributor to my fork.

2016-09-26 17:10 UTC, gesellc commented
How about merging this to main?

Admittedly, there are a few ways to refactor this
- Do we really need the trusty image with sudo on Travis?
- Should we move the different dependencies (backend, frontend, test dependencies) into scripts?

but I'd rather see how we use the protractor tests locally for development and let this usage inform future refactorings.

That way we can start test-driving new features now...  :-)

2016-09-29 19:50 UTC, sturmf approved these changes

2016-09-29 19:53 UTC, merged